DEBUG = True

BIND_HOST = "0.0.0.0"
BIND_PORT = 8000
ANTHROPIC_API_KEY_ENV_VAR = "ANTHROPIC_API_KEY"
MODEL = "claude-sonnet-4-6"
MODEL_MAX_TOKENS = 16000
MODEL_CALL_RETRIES = 2
MODEL_CALL_RETRY_DELAY_MS = 0
GITHUB_TOKEN_ENV_VAR = "GITHUB_TOKEN"
DOWNLOAD_RETRIES = 1
DOWNLOAD_RETRY_DELAY_MS = 800
DOWNLOAD_CONCURRENCY = 6
DOWNLOAD_LIMIT_STAGE_1_FILES = 12
DOWNLOAD_LIMIT_STAGE_1_MB = 12
